name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    strategy:
      fail-fast: true
      matrix:
        include:
          - product: ec
            runner: ubuntu-22.04
            skip: run
          - product: ec
            runner: ubuntu-24.04
            skip: run
          - product: ec
            runner: ubuntu-22.04-arm
            skip: run
          - product: ec
            runner: ubuntu-24.04-arm
            skip: run
          - product: ec
            runner: self-hosted-generic-vm-amd64
          - product: ec
            runner: self-hosted-generic-vm-arm64
          - product: osi
            runner: self-hosted-generic-vm-amd64
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install ORAS
        if: matrix.runner == 'ubuntu-24.04' || matrix.runner == 'ubuntu-24.04-arm' || matrix.runner == 'ubuntu-22.04-arm' || matrix.runner == 'self-hosted-generic-vm-arm64'
        run: |
          OS="$(uname -s | tr A-Z a-z)"
          ARCH=$(uname -m | sed -e 's/x86_64/amd64/g' -e 's/aarch64/arm64/g')
          VERSION="1.3.4"
          FILE="oras_${VERSION}_${OS}_${ARCH}.tar.gz"
          if [ "$ARCH" = amd64 ]; then
            SUM=f27adb935022d94df8dc77719c322dda592c78a0d57a6f7dcdd8d900b248c454
          else
            SUM=15702c6e3a4a56a8bd8ac5c17efdbcab56d9bada661ccbcf017f5b10c1d89399
          fi
          curl -LO "https://github.com/oras-project/oras/releases/download/v${VERSION}/${FILE}"
          echo "$SUM $FILE" | sha256sum -c -
          mkdir -p oras-install/
          tar -zxf "$FILE" -C oras-install/
          sudo install -o 0 -g 0 -m 0755 oras-install/oras /usr/local/bin/oras
          rm -rf "$FILE" oras-install/

      - name: Install binfmt
        if: matrix.runner == 'ubuntu-24.04-arm' || matrix.runner == 'ubuntu-22.04-arm' || matrix.runner == 'self-hosted-generic-vm-arm64'
        run: |
          docker run --privileged --rm tonistiigi/binfmt@sha256:400a4873b838d1b89194d982c45e5fb3cda4593fbfd7e08a02e76b03b21166f0 --install amd64

      - name: Install
        run: |
          make
          sudo install -m 0755 openvas-deployment /usr/bin/openvas-deployment
          echo '${{ secrets.FEED_KEY }}' > gsf.key
          echo '${{ secrets.OCI_CERT }}' > oci-client.cert
          echo '${{ secrets.OCI_KEY }}' > oci-client.key

      - name: CI ${{ matrix.product }}
        env:
          MHOSTS: yes
          SKIP: ${{ matrix.skip }}
        run: bash regress/${{ matrix.product }}.sh
