name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    strategy:
      fail-fast: true
      matrix:
        include:
          - product: ec
            runner: ubuntu-22.04
          - product: ec
            runner: ubuntu-24.04
          - product: ec
            runner: ubuntu-22.04-arm
          - product: ec
            runner: ubuntu-24.04-arm
          - product: ec
            runner: self-hosted-generic-vm-amd64
          - product: osi
            runner: self-hosted-generic-vm-amd64
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install ORAS
        if: matrix.runner == 'ubuntu-24.04' || matrix.runner == 'ubuntu-24.04-arm' || matrix.runner == 'ubuntu-22.04-arm'
        run: |
          OS="$(uname -s | tr A-Z a-z)"
          ARCH=$(uname -m | sed -e 's/x86_64/amd64/g')
          VERSION="1.3.4"
          echo "Download: https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_${OS}_${ARCH}.tar.gz"
          curl -LO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_${OS}_${ARCH}.tar.gz"
          mkdir -p oras-install/
          tar -zxf oras_${VERSION}_${OS}_${ARCH}.tar.gz -C oras-install/
          sudo chown root:0 oras-install/oras
          sudo mv oras-install/oras /usr/local/bin/
          rm -rf oras_${VERSION}_${OS}_${ARCH}.tar.gz oras-install/

      - name: Install
        run: |
          make
          sudo install -m 0755 openvas-deployment /usr/bin/openvas-deployment
          echo '${{ secrets.FEED_KEY }}' > gsf.key
          echo '${{ secrets.OCI_CERT }}' > oci-client.cert
          echo '${{ secrets.OCI_KEY }}' > oci-client.key

      - name: CI ${{ matrix.product }}
        env:
          MHOSTS: yes
        run: bash regress/${{ matrix.product }}.sh
