name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    strategy:
      fail-fast: true
      matrix:
        include:
          - image: fedora:43
            product: ec
            runner: self-hosted-generic-vm-amd64
          - image: fedora:44
            product: ec
            runner: self-hosted-generic-vm-amd64
          - image: ubuntu:22.04
            product: ec
            runner: self-hosted-generic-vm-amd64
          - image: ubuntu:24.04
            product: ec
            runner: self-hosted-generic-vm-amd64
          - image: archlinux:latest
            product: ec
            runner: self-hosted-generic-vm-amd64
          - image: debian:12
            product: ec
            runner: self-hosted-generic-vm-amd64
          - image: debian:13
            product: ec
            runner: self-hosted-generic-vm-amd64
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        
      - name: Install binfmt
        if: matrix.runner == 'self-hosted-generic-vm-arm64'
        run: |
          docker run --privileged --rm tonistiigi/binfmt@sha256:400a4873b838d1b89194d982c45e5fb3cda4593fbfd7e08a02e76b03b21166f0 --install amd64

      - name: Install test credentials
        run: |
          umask 077
          echo '${{ secrets.FEED_KEY }}' > gsf.key
          echo '${{ secrets.OCI_CERT }}' > oci-client.cert
          echo '${{ secrets.OCI_KEY }}' > oci-client.key

      - name: Run regression test ${{ matrix.product }}
        env:
          MHOSTS: 'yes'
        run: |
          docker run --rm \
            --name openvas-deployment-ci \
            --network host \
            --user 0 \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v /etc/docker/certs.d:/etc/docker/certs.d \
            -v "$(pwd)":/workspace \
            -w /workspace \
            ${{ matrix.image }} \
            bash -c 'bash regress/ci/install-dependencies.sh && bash regress/${{ matrix.product }}.sh'
